package at.researchstudio.sat.merkmalservice.vocab.ifc;

import java.util.Objects;

/**
 * represents * IfcUnitEnum - see
 * https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcunitenum.htm *
 * IfcDerivedUnitEnum - see
 * https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcderivedunitenum.htm
 */
public enum IfcUnitType {
    // entries for IfcUnitEnum
    ABSORBEDDOSEUNIT("ABSORBEDDOSEUNIT"),
    AMOUNTOFSUBSTANCEUNIT("AMOUNTOFSUBSTANCEUNIT"),
    AREAUNIT("AREAUNIT"),
    DOSEEQUIVALENTUNIT("DOSEEQUIVALENTUNIT"),
    ELECTRICCAPACITANCEUNIT("ELECTRICCAPACITANCEUNIT"),
    ELECTRICCHARGEUNIT("ELECTRICCHARGEUNIT"),
    ELECTRICCONDUCTANCEUNIT("ELECTRICCONDUCTANCEUNIT"),
    ELECTRICCURRENTUNIT("ELECTRICCURRENTUNIT"),
    ELECTRICRESISTANCEUNIT("ELECTRICRESISTANCEUNIT"),
    ELECTRICVOLTAGEUNIT("ELECTRICVOLTAGEUNIT"),
    ELECTRIVOLTAGEUNIT("ELECTRICVOLTAGEUNIT"),
    ENERGYUNIT("ENERGYUNIT"),
    FORCEUNIT("FORCEUNIT"),
    FREQUENCYUNIT("FREQUENCYUNIT"),
    ILLUMINANCEUNIT("ILLUMINANCEUNIT"),
    INDUCTANCEUNIT("INDUCTANCEUNIT"),
    LENGTHUNIT("LENGTHUNIT"),
    LUMINOUSFLUXUNIT("LUMINOUSFLUXUNIT"),
    LUMINOUSINTENSITYUNIT("LUMINOUSINTENSITYUNIT"),
    MAGNETICFLUXDENSITYUNIT("MAGNETICFLUXDENSITYUNIT"),
    MAGNETICFLUXUNIT("MAGNETICFLUXUNIT"),
    MASSUNIT("MASSUNIT"),
    PLANEANGLEUNIT("PLANEANGLEUNIT"),
    POWERUNIT("POWERUNIT"),
    PRESSUREUNIT("PRESSUREUNIT"),
    RADIOACTIVITYUNIT("RADIOACTIVITYUNIT"),
    SOLIDANGLEUNIT("SOLIDANGLEUNIT"),
    THERMODYNAMICTEMPERATUREUNIT("THERMODYNAMICTEMPERATUREUNIT"),
    TIMEUNIT("TIMEUNIT"),
    VOLUMEUNIT("VOLUMEUNIT"),
    USERDEFINED("USERDEFINED"),

    // entries for IfcDerivedUnitEnum

    ACCELERATIONUNIT("ACCELERATIONUNIT"),
    ANGULARVELOCITYUNIT("ANGULARVELOCITYUNIT"),
    AREADENSITYUNIT("AREADENSITYUNIT"),
    COMPOUNDPLANEANGLEUNIT("COMPOUNDPLANEANGLEUNIT"),
    CURVATUREUNIT("CURVATUREUNIT"),
    DYNAMICVISCOSITYUNIT("DYNAMICVISCOSITYUNIT"),
    HEATFLUXDENSITYUNIT("HEATFLUXDENSITYUNIT"),
    HEATINGVALUEUNIT("HEATINGVALUEUNIT"),
    INTEGERCOUNTRATEUNIT("INTEGERCOUNTRATEUNIT"),
    IONCONCENTRATIONUNIT("IONCONCENTRATIONUNIT"),
    ISOTHERMALMOISTURECAPACITYUNIT("ISOTHERMALMOISTURECAPACITYUNIT"),
    KINEMATICVISCOSITYUNIT("KINEMATICVISCOSITYUNIT"),
    LINEARFORCEUNIT("LINEARFORCEUNIT"),
    LINEARMOMENTUNIT("LINEARMOMENTUNIT"),
    LINEARSTIFFNESSUNIT("LINEARSTIFFNESSUNIT"),
    LINEARVELOCITYUNIT("LINEARVELOCITYUNIT"),
    LUMINOUSINTENSITYDISTRIBUTIONUNIT("LUMINOUSINTENSITYDISTRIBUTIONUNIT"),
    MASSDENSITYUNIT("MASSDENSITYUNIT"),
    MASSFLOWRATEUNIT("MASSFLOWRATEUNIT"),
    MASSPERLENGTHUNIT("MASSPERLENGTHUNIT"),
    MODULUSOFELASTICITYUNIT("MODULUSOFELASTICITYUNIT"),
    MODULUSOFLINEARSUBGRADEREACTIONUNIT("MODULUSOFLINEARSUBGRADEREACTIONUNIT"),
    MODULUSOFROTATIONALSUBGRADEREACTIONUNIT("MODULUSOFROTATIONALSUBGRADEREACTIONUNIT"),
    MODULUSOFSUBGRADEREACTIONUNIT("MODULUSOFSUBGRADEREACTIONUNIT"),
    MOISTUREDIFFUSIVITYUNIT("MOISTUREDIFFUSIVITYUNIT"),
    MOLECULARWEIGHTUNIT("MOLECULARWEIGHTUNIT"),
    MOMENTOFINERTIAUNIT("MOMENTOFINERTIAUNIT"),
    PHUNIT("PHUNIT"),
    PLANARFORCEUNIT("PLANARFORCEUNIT"),
    ROTATIONALFREQUENCYUNIT("ROTATIONALFREQUENCYUNIT"),
    ROTATIONALMASSUNIT("ROTATIONALMASSUNIT"),
    ROTATIONALSTIFFNESSUNIT("ROTATIONALSTIFFNESSUNIT"),
    SECTIONAREAINTEGRALUNIT("SECTIONAREAINTEGRALUNIT"),
    SECTIONMODULUSUNIT("SECTIONMODULUSUNIT"),
    SHEARMODULUSUNIT("SHEARMODULUSUNIT"),
    SOUNDPOWERLEVELUNIT("SOUNDPOWERLEVELUNIT"),
    SOUNDPOWERUNIT("SOUNDPOWERUNIT"),
    SOUNDPRESSURELEVELUNIT("SOUNDPRESSURELEVELUNIT"),
    SOUNDPRESSUREUNIT("SOUNDPRESSUREUNIT"),
    SPECIFICHEATCAPACITYUNIT("SPECIFICHEATCAPACITYUNIT"),
    TEMPERATUREGRADIENTUNIT("TEMPERATUREGRADIENTUNIT"),
    TEMPERATURERATEOFCHANGEUNIT("TEMPERATURERATEOFCHANGEUNIT"),
    THERMALADMITTANCEUNIT("THERMALADMITTANCEUNIT"),
    THERMALCONDUCTANCEUNIT("THERMALCONDUCTANCEUNIT"),
    THERMALEXPANSIONCOEFFICIENTUNIT("THERMALEXPANSIONCOEFFICIENTUNIT"),
    THERMALRESISTANCEUNIT("THERMALRESISTANCEUNIT"),
    THERMALTRANSMITTANCEUNIT("THERMALTRANSMITTANCEUNIT"),
    TORQUEUNIT("TORQUEUNIT"),
    VAPORPERMEABILITYUNIT("VAPORPERMEABILITYUNIT"),
    VOLUMETRICFLOWRATEUNIT("VOLUMETRICFLOWRATEUNIT"),
    WARPINGCONSTANTUNIT("WARPINGCONSTANTUNIT"),
    WARPINGMOMENTUNIT("WARPINGMOMENTUNIT"),

    UNKNOWN();

    // declaring private variable for getting values
    private final String[] typeUris;

    IfcUnitType(String... typeUris) {
        this.typeUris = typeUris;
    }

    /**
     * retrieves corresponding enum value for the given unitType
     *
     * @param unitType non null
     * @return corresponding Enum Value
     * @throws IllegalArgumentException if no enum value is found
     * @throws NullPointerException if unitType was null
     */
    public static IfcUnitType fromString(String unitType)
            throws IllegalArgumentException, NullPointerException {
        Objects.requireNonNull(unitType, "No enum IfcUnitType for nullvalue");

        for (IfcUnitType type : IfcUnitType.values()) {
            for (String enumUri : type.typeUris) {
                if (unitType.contains("#")) {
                    String[] splitUnitType = unitType.split("#");
                    if (splitUnitType.length == 2 && enumUri.equals(splitUnitType[1])) {
                        return type;
                    }
                }
                if (enumUri.equals(unitType)) {
                    return type;
                }
            }
        }
        throw new IllegalArgumentException("No enum constant for value: '" + unitType + "'");
    }
}
