PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (CONCAT(
    "public static final Prefix ",
    ?constName,
    ' = prefixFromLocalname("',
    STR(?localName),
    "\");"
    ) as ?javacode) where
{
    ?prefix a qudt:Prefix;
    BIND(REPLACE(STR(?prefix), "^.+/", "") as ?localName)
    BIND(REPLACE(?localName, "-", "__") as ?constName)
} order by ?prefix
