PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# bind ?baseUnit and ?prefix, get the scaled unit
SELECT * where
{
    ?unit a qudt:Unit;
       rdfs:label ?label ;
       qudt:isScalingOf ?baseUnit ;
       qudt:prefix ?prefix ;
       qudt:isScalingOf ?baseUnit .

    ?baseUnit a qudt:Unit .

    ?prefix a qudt:Prefix .

    optional {
       ?unit qudt:conversionMultiplier ?conversionMultiplier
    }
    optional {
        ?unit qudt:hasQuantityKind ?quantityKind
    }
    optional {
           ?unit qudt:conversionOffset ?conversionOffset
        }
    optional {
       ?unit qudt:symbol ?symbol
    }
    optional {
        ?unit qudt:isScalingOf ?scalingOf
    }
    optional {
            ?unit qudt:hasDimensionVector ?dimensionVector
    }
}
